### ISSUE TITLE
Call cannot start on Chromium browser on Linux

### ISSUE THREAD

**Issue by johncrawley** [Pedal-Intelligence/saypi-userscript#128]
Steps to reproduce:
 - Open the Chromium browser on Linux.
 - Navigate to the Chrome Store and install the SayPi extension.
 - Navigate to the pi.ai webstite
 - Start a call

Notice that the call does not start, with a mic error appearing on-screen.

This appears to have been introduced with the "Set mime types for wasm and onnx responses" commit. Checking out and building the previous commit facilitated a successful call startup.

 The following is logged to the console:

saypi.user.js:761 Encountered an error while loading model file. Please make sure silero_vad.onnx, included with @ricky0123/vad-web, is available at the specified path:
      /silero_vad.onnx
      If need be, you can customize the model file location using the `modelURL` option.
new @ saypi.user.js:761
await in new
new @ saypi.user.js:703
(anonymous) @ saypi.user.js:34580
fulfilled @ saypi.user.js:34384
Promise.then
step @ saypi.user.js:34386
(anonymous) @ saypi.user.js:34387
AudioInputMachine_awaiter @ saypi.user.js:34383
setupRecording @ saypi.user.js:34555
(anonymous) @ saypi.user.js:34831
acquireMicrophone @ saypi.user.js:34830
Interpreter._exec @ saypi.user.js:25464
handleAction @ saypi.user.js:24458
processBlock @ saypi.user.js:24489
resolveActions @ saypi.user.js:24514
StateNode.resolveTransition @ saypi.user.js:27918
StateNode.transition @ saypi.user.js:27841
(anonymous) @ saypi.user.js:26157
provide @ saypi.user.js:24885
Interpreter._nextState @ saypi.user.js:26156
(anonymous) @ saypi.user.js:25303
Scheduler.process @ saypi.user.js:24861
Scheduler.schedule @ saypi.user.js:24840
Interpreter.send @ saypi.user.js:25299
(anonymous) @ saypi.user.js:38867
emit @ saypi.user.js:1911
setupRecording @ saypi.user.js:40917
Interpreter._exec @ saypi.user.js:25366
handleAction @ saypi.user.js:24458
processBlock @ saypi.user.js:24489
resolveActions @ saypi.user.js:24514
StateNode.resolveTransition @ saypi.user.js:27918
StateNode.transition @ saypi.user.js:27841
(anonymous) @ saypi.user.js:26157
provide @ saypi.user.js:24885
Interpreter._nextState @ saypi.user.js:26156
(anonymous) @ saypi.user.js:25303
Scheduler.process @ saypi.user.js:24861
Scheduler.schedule @ saypi.user.js:24840
Interpreter.send @ saypi.user.js:25299
(anonymous) @ saypi.user.js:42677
Show 40 more frames
Show less
saypi.user.js:34587 VAD microphone failed to load. Error: no available backend found. ERR: [wasm] TypeError: Failed to fetch, [cpu] Error: previous call to 'initWasm()' failed.
    at Dn (saypi.user.js:20633:1787)
    at async a.create (saypi.user.js:20633:18248)
    at async Silero.init (saypi.user.js:493:29)
    at async __webpack_modules__.8283.Silero.new (saypi.user.js:524:5)
    at async AudioNodeVAD.new (saypi.user.js:758:21)
    at async MicVAD.new (saypi.user.js:703:30)
(anonymous) @ saypi.user.js:34587
rejected @ saypi.user.js:34385
Promise.then
step @ saypi.user.js:34386
fulfilled @ saypi.user.js:34384
Promise.then
step @ saypi.user.js:34386
(anonymous) @ saypi.user.js:34387
AudioInputMachine_awaiter @ saypi.user.js:34383
setupRecording @ saypi.user.js:34555
(anonymous) @ saypi.user.js:34831
acquireMicrophone @ saypi.user.js:34830
Interpreter._exec @ saypi.user.js:25464
handleAction @ saypi.user.js:24458
processBlock @ saypi.user.js:24489
resolveActions @ saypi.user.js:24514
StateNode.resolveTransition @ saypi.user.js:27918
StateNode.transition @ saypi.user.js:27841
(anonymous) @ saypi.user.js:26157
provide @ saypi.user.js:24885
Interpreter._nextState @ saypi.user.js:26156
(anonymous) @ saypi.user.js:25303
Scheduler.process @ saypi.user.js:24861
Scheduler.schedule @ saypi.user.js:24840
Interpreter.send @ saypi.user.js:25299
(anonymous) @ saypi.user.js:38867
emit @ saypi.user.js:1911
setupRecording @ saypi.user.js:40917
Interpreter._exec @ saypi.user.js:25366
handleAction @ saypi.user.js:24458
processBlock @ saypi.user.js:24489
resolveActions @ saypi.user.js:24514
StateNode.resolveTransition @ saypi.user.js:27918
StateNode.transition @ saypi.user.js:27841
(anonymous) @ saypi.user.js:26157
provide @ saypi.user.js:24885
Interpreter._nextState @ saypi.user.js:26156
(anonymous) @ saypi.user.js:25303
Scheduler.process @ saypi.user.js:24861
Scheduler.schedule @ saypi.user.js:24840
Interpreter.send @ saypi.user.js:25299
(anonymous) @ saypi.user.js:42677
Show 40 more frames
Show less
saypi.user.js:34819 Microphone error: Failed to access microphone: no available backend found. ERR: [wasm] TypeError: Failed to fetch, [cpu] Error: previous call to 'initWasm()' failed. Error: no available backend found. ERR: [wasm] TypeError: Failed to fetch, [cpu] Error: previous call to 'initWasm()' failed.
    at Dn (saypi.user.js:20633:1787)
    at async a.create (saypi.user.js:20633:18248)
    at async Silero.init (saypi.user.js:493:29)
    at async __webpack_modules__.8283.Silero.new (saypi.user.js:524:5)
    at async AudioNodeVAD.new (saypi.user.js:758:21)
    at async MicVAD.new (saypi.user.js:703:30)

**Comment by johncrawley** [comment]
Not reproducible on Chrome browser (running in Flatpak).

**Comment by johncrawley** [comment]
Able to reproduce on Chrome under Flatpak, Linux today, and briefly under Firefox until reinstall from the add-on website. It's possibly some problem with my own environment.

**Comment by johncrawley** [comment]
Currently unable to reproduce this issue.
